/**
 * Created by chaika on 02.02.16.
 */
var fs = require('fs');
var ejs = require('ejs');


//exports.PizzaMenu_OneItem = ejs.compile(fs.readFileSync('./Frontend/templates/PizzaMenu_OneItem.ejs', "utf8"));

exports.PizzaMenu_OneItem = ejs.compile("<%\r\n\r\nfunction getIngredientsArray(pizza) {\r\n    var content = pizza.content;\r\n    var result = [];\r\n\r\n\r\n    Object.keys(content).forEach(function(key){\r\n\r\n        result = result.concat(content[key]);\r\n    });\r\n        return result;\r\n}\r\n\r\n   %>\r\n<div class=\"col-md-6 col-lg-4\">\r\n    <div class=\"thumbnail pizza-card\">\r\n               <% if(pizza.is_new) { %>\r\n        <span class=\"label label-danger pull-right\">Нова</span>\r\n        <% } else if(pizza.is_popular) {%>\r\n        <span class=\"label label-success pull-right\">Популярна</span>\r\n        <% } %>\r\n <img class=\"pizza-icon\" src=\"<%= pizza.icon %>\" alt=\"Pizza\">  \r\n         <div class=\"caption\">\r\n           <h3><%= pizza.title %></h3>\r\n            <p class=\"remark\"><%= pizza.type %></p>\r\n            <p class=\"description\">\r\n              <%= getIngredientsArray(pizza).join(\", \") %>\r\n            </p>\r\n        </div>\r\n              <% if (pizza.small_size){ %>\r\n      <div  class=\"btn-group-vertical text-center buy\">\r\n             <div>       <img src=\"assets/images/size-icon.svg\">\r\n                    <span><%= pizza.small_size.size %></span>\r\n                </div>\r\n                   <div>\r\n         <img src=\"assets/images/weight.svg\">\r\n                    <span><%= pizza.small_size.weight %></span>\r\n                </div>\r\n                <h2>\r\n                    <%= pizza.small_size.price %><\h2>\r\n<h5> грн.</h5>\r\n                            <button type=\"button\" class=\"btn btn-warning buy-small buy-button-small\" role=\"button\">Купити</a>\r\n</button>\r\n</div>                  <% } %>\r\n            <% if (pizza.big_size) { %>\r\n                 <div class=\"btn-group-vertical text-center buy\">\r\n<div>                    <img src=\"assets/images/size-icon.svg\">\r\n                    <span><%= pizza.big_size.size %></span>\r\n                </div>\r\n                <div>\r\n                    <img src=\"assets/images/weight.svg\">\r\n                    <span><%= pizza.big_size.weight %></span>\r\n                </div>\r\n                <h2>\r\n                    <%= pizza.big_size.price %><\h2>\r\n <h5> грн.</h5>\r\n                         <button type=\"button\" class=\"btn btn-warning buy-big buy-button-big\" role=\"button\">Купити</a>\r\n  </button>\r\n         </div>          <% } %>\r\n        </div>\r\n    </div>");

//exports.PizzaCart_OneItem = ejs.compile(fs.readFileSync('./Frontend/templates/PizzaCart_OneItem.ejs', "utf8"));

exports.PizzaCart_OneItem = ejs.compile("<div class=\"order-one ng-scope\">\r\n\t\t\t        <img class=\"img-aside pizza-icon\" alt=\"Піца\" src=\"assets/images/pizza_2.jpg\">\r\n\t\t\t        <p class=\"bold mb10 ng-scope\">\r\n\t\t\t            <span class=\"order-title\" style=\"font-size: 20px;\"><%= pizza.title %> (<%=size%><%if(size==pizza.small_size){%>Мала<%}else if(size==pizza.big_size){%>Велика<%} %>) </span>\r\n\t\t\t        </p>\r\n\t\t\t        <div class=\"order-text\">\r\n\t\t\t            <img src=\"assets/images/size-icon.svg\">\r\n\t\t\t            <span>30</span>\r\n\t\t\t            <img src=\"assets/images/weight.svg\">\r\n\t\t\t            <span>160</span>\r\n\t\t\t        </div>\r\n\t\t\t        <div>\r\n\t\t\t            <span>Ціна: <%= pizza[size].price %> грн.</span>\r\n\t\t\t            <a class=\"minus btn btn-xs btn-danger btn-circle\" >\r\n\t\t\t                <i class=\"glyphicon glyphicon-minus icon-white\">\r\n\t\t\t                </i>\r\n\t\t\t            </a>\r\n\t\t\t            <span class=\"label order-pizza-count\" style=\"color:black;\"><%= quantity %></span>\r\n\t\t\t            <a class=\"plus btn btn-xs btn-success btn-circle`\" >\r\n\t\t\t                <i class=\"glyphicon glyphicon-plus icon-white\">\r\n\r\n\t\t\t                </i>\r\n\t\t\t            </a>\r\n\t\t\t            <a class=\"count-clear btn btn-xs btn-default btn-circle \" >\r\n\t\t\t                <i class=\"glyphicon glyphicon-remove icon-white\">\r\n\r\n\t\t\t                </i>\r\n\t\t\t            </a>\r\n\t\t\t        </div>\r\n\t\t\t    </div>");
